-- USERS (CLIENTS)
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADMINS
CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- FLIGHTS
CREATE TABLE IF NOT EXISTS flights (
  id INT AUTO_INCREMENT PRIMARY KEY,
  flight_no VARCHAR(20) NOT NULL,
  airline VARCHAR(80) NOT NULL,
  from_city VARCHAR(80) NOT NULL,
  from_code VARCHAR(10) NOT NULL,
  to_city VARCHAR(80) NOT NULL,
  to_code VARCHAR(10) NOT NULL,
  departure_datetime DATETIME NOT NULL,
  arrival_datetime DATETIME NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  total_seats INT NOT NULL,
  seats_available INT NOT NULL,
  status ENUM('SCHEDULED','CANCELLED') DEFAULT 'SCHEDULED'
);

-- BOOKINGS
CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  flight_id INT NOT NULL,
  pnr VARCHAR(16) NOT NULL UNIQUE,
  passengers INT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  booking_status ENUM('PENDING_PAYMENT','CONFIRMED','CANCELLED') DEFAULT 'PENDING_PAYMENT',
  payment_status ENUM('UNPAID','PAID','FAILED') DEFAULT 'UNPAID',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (flight_id) REFERENCES flights(id)
);

-- PAYMENTS (optional detail table)
CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  booking_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  method VARCHAR(50) NOT NULL,
  status ENUM('SUCCESS','FAILED') DEFAULT 'SUCCESS',
  paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id)
);
<?php echo password_hash('admin123', PASSWORD_DEFAULT); ?>
